# Generated by Django 5.0.9 on 2025-07-16 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neksio_api', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('ref_no', models.CharField(max_length=50)),
                ('invoice_no', models.CharField(max_length=40)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('transaction_type', models.CharField(choices=[('SALE', 'SALE'), ('SALE_REFUND', 'SALE_REFUND'), ('PURCHASE', 'PURCHASE'), ('PURCHASE_REFUND', 'PURCHASE_REFUND'), ('JOURNAL_ENTRY', 'JOURNAL_ENTRY'), ('PAYMENT_VOUCHER', 'PAYMENT_VOUCHER'), ('RECEIPT_VOUCHER', 'RECEIPT_VOUCHER'), ('CREDIT_NOTE', 'CREDIT_NOTE'), ('DEBIT_NOTE', 'DEBIT_NOTE')], max_length=25)),
                ('line_extension_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_exclusive_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_inclusive_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prepaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('returned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELED')], max_length=15)),
                ('refunded', models.BooleanField(default=False)),
                ('refund_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('qrcode', models.TextField(blank=True, null=True)),
                ('is_return', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='neksio_api.businessprofile')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='neksio_api.parties')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_method', to='neksio_api.paymenttypes')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_accounts', to='neksio_api.financialaccounts')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='neksio_api.businessprofile')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='transactions.journalline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JournalProductDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_inclusive_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_transactions', to='transactions.journalline')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='products.productitem')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='neksio_api.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxTransactions',
            fields=[
                ('icv', models.IntegerField(auto_created=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('document_currency', models.CharField(max_length=5)),
                ('tax_currency', models.CharField(max_length=5)),
                ('previous_invoice_hash', models.CharField(max_length=250)),
                ('qrcode', models.TextField(blank=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('latest_delivery_date', models.DateField(blank=True, null=True)),
                ('instruction_note', models.TextField(blank=True, max_length=50, null=True)),
                ('billing_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_type', models.CharField(choices=[('REPORTING_INVOICE', 'REPORTING_INVOICE'), ('REPORTING_CREDIT_NOTE', 'REPORTING_CREDIT_NOTE'), ('REPORTING_DEBIT_NOTE', 'REPORTING_DEBIT_NOTE'), ('CLEARANCE_INVOICE', 'CLEARANCE_INVOICE'), ('CLEARANCE_CREDIT_NOTE', 'CLEARANCE_CREDIT_NOTE'), ('CLEARANCE_DEBIT_NOTE', 'CLEARANCE_DEBIT_NOTE')], max_length=25)),
                ('invoice_status', models.CharField(choices=[('REPORTING_INVOICE', 'REPORTING_INVOICE'), ('REPORTING_CREDIT_NOTE', 'REPORTING_CREDIT_NOTE'), ('REPORTING_DEBIT_NOTE', 'REPORTING_DEBIT_NOTE'), ('CLEARANCE_INVOICE', 'CLEARANCE_INVOICE'), ('CLEARANCE_CREDIT_NOTE', 'CLEARANCE_CREDIT_NOTE'), ('CLEARANCE_DEBIT_NOTE', 'CLEARANCE_DEBIT_NOTE')], max_length=25)),
                ('response_message', models.TextField(blank=True, max_length=500, null=True)),
                ('xml', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zatca_transactions', to='transactions.journalline')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='neksio_api.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['invoice_no'], name='transaction_invoice_21a0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_bc0572_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['party'], name='transaction_party_i_c6ad92_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['date_time'], name='transaction_date_ti_4729f8_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['location'], name='transaction_locatio_8bfe6b_idx'),
        ),
        migrations.AddIndex(
            model_name='journaldetail',
            index=models.Index(fields=['transaction'], name='transaction_transac_90c824_idx'),
        ),
        migrations.AddIndex(
            model_name='journaldetail',
            index=models.Index(fields=['account'], name='transaction_account_49ebeb_idx'),
        ),
    ]
