# Generated by Django 4.2.8 on 2025-07-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaldetail',
            name='account_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='journalproductdetail',
            name='item_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
