# Generated by Django 5.0.14 on 2025-07-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_journaldetail_account_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='data_collection',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='is_sync',
            field=models.BooleanField(default=False),
        ),
    ]
