# Generated by Django 5.0.14 on 2025-08-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_journalline_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
