# Generated by Django 5.0.14 on 2025-08-06 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0010_paymentshistory_duration'),
        ('transactions', '0005_journalline_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayClosing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('returns', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='neksio_api.businessprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayClosingDetail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_type', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('day_closing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closing_detail', to='transactions.dayclosing')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='neksio_api.businessprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug', 'day_closing'], name='transaction_slug_910ed9_idx')],
            },
        ),
    ]
