# Generated by Django 5.0.14 on 2025-08-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_dayclosing_dayclosingdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalline',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('SALE', 'SALE'), ('SALE_REFUND', 'SALE_REFUND'), ('PURCHASE', 'PURCHASE'), ('PURCHASE_REFUND', 'PURCHASE_REFUND'), ('JOURNAL_ENTRY', 'JOURNAL_ENTRY'), ('PAYMENT_VOUCHER', 'PAYMENT_VOUCHER'), ('RECEIPT_VOUCHER', 'RECEIPT_VOUCHER'), ('CREDIT_NOTE', 'CREDIT_NOTE'), ('DEBIT_NOTE', 'DEBIT_NOTE'), ('REVERSE_PAYMENT_VOUCHER', 'REVERSE_PAYMENT_VOUCHER'), ('REVERSE_RECEIPT_VOUCHER', 'REVERSE_RECEIPT_VOUCHER'), ('REVERSE_JOURNAL_ENTRY', 'REVERSE_JOURNAL_ENTRY')], max_length=25),
        ),
    ]
