# Generated by Django 5.0.14 on 2025-08-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_journalline_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='carriage_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
