# Generated by Django 5.0.14 on 2025-08-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_journalline_carriage_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='carriage_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
