# Generated by Django 5.0.14 on 2025-09-02 06:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_journalproductdetail_ime_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalproductdetail',
            name='ime_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
    ]
