# Generated by Django 5.0.14 on 2025-09-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_journalproductdetail_ime_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalproductdetail',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
