# Generated by Django 5.0.14 on 2025-10-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0023_alter_invoicesettings_name'),
        ('transactions', '0013_alter_journalline_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='media_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='neksio_api.mediafiles'),
        ),
    ]
