# Generated by Django 5.0.9 on 2025-07-16 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neksio_api', '0001_initial'),
        ('zatca_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='branch',
            field=models.ManyToManyField(blank=True, to='zatca_api.businesslocation', verbose_name='branch_invoice'),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='neksio_api.businessprofile', verbose_name='business_invoice'),
        ),
        migrations.AddField(
            model_name='mediafiles',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='neksio_api.businessprofile'),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='neksio_api.mediafiles', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='parties',
            name='chart_of_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neksio_api.financialaccounts'),
        ),
        migrations.AddField(
            model_name='parties',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='neksio_api.businessprofile'),
        ),
        migrations.AddField(
            model_name='parties',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='neksio_api.mediafiles', verbose_name='Photo'),
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('neksio_api.parties',),
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'ordering': ['-created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('neksio_api.parties',),
        ),
        migrations.AddField(
            model_name='paymentshistory',
            name='business_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_history', to='neksio_api.businessprofile'),
        ),
        migrations.AddField(
            model_name='paymentshistory',
            name='package_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_package', to='neksio_api.businesspackages'),
        ),
        migrations.AddField(
            model_name='paymentshistory',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='payments'),
        ),
        migrations.AddField(
            model_name='paymenttypes',
            name='chart_of_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='neksio_api.financialaccounts'),
        ),
        migrations.AddField(
            model_name='paymenttypes',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='neksio_api.businessprofile'),
        ),
        migrations.AddField(
            model_name='taxtypes',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='neksio_api.businessprofile'),
        ),
        migrations.AddIndex(
            model_name='accountsetting',
            index=models.Index(fields=['id', 'location'], name='neksio_api__id_d42195_idx'),
        ),
    ]
