# Generated by Django 4.2.8 on 2025-07-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='chart_of_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neksio_api.financialaccounts'),
        ),
    ]
