# Generated by Django 4.2.8 on 2025-07-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0003_alter_parties_chart_of_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='chart_of_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neksio_api.financialaccounts'),
        ),
    ]
