# Generated by Django 5.0.14 on 2025-07-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0005_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='financial_account',
            new_name='chart_of_account',
        ),
    ]
