# Generated by Django 5.0.14 on 2025-08-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0006_rename_financial_account_employees_chart_of_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='chart_of_account',
            field=models.OneToOneField(blank=True, limit_choices_to=models.Q(('type', 'Asset')), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='neksio_api.financialaccounts'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='chart_of_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='neksio_api.financialaccounts'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='chart_of_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='investor', to='neksio_api.financialaccounts'),
        ),
        migrations.AlterField(
            model_name='parties',
            name='chart_of_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='neksio_api.financialaccounts'),
        ),
    ]
