# Generated by Django 5.0.9 on 2025-08-05 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0007_alter_bankaccount_chart_of_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessWhatsappProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collections', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager_id', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_account_id', models.CharField(max_length=100, unique=True)),
                ('authorize', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
