# Generated by Django 5.0.9 on 2025-08-05 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0008_businesswhatsappprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswhatsappprofile',
            name='business_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_whatsapp_profile', to='neksio_api.businessprofile'),
        ),
    ]
