# Generated by Django 5.0.14 on 2025-08-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0009_businesswhatsappprofile_business_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentshistory',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
