# Generated by Django 5.0.9 on 2025-08-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0010_paymentshistory_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspackages',
            name='package_code',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
