# Generated by Django 5.0.14 on 2025-08-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0011_businesspackages_package_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswhatsappprofile',
            name='instance_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='businesswhatsappprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='businesswhatsappprofile',
            name='whatsapp_integration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
