# Generated by Django 5.0.14 on 2025-08-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0012_businesswhatsappprofile_instance_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswhatsappprofile',
            name='qrcode',
            field=models.BooleanField(default=False),
        ),
    ]
