# Generated by Django 5.0.9 on 2025-08-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0013_businesswhatsappprofile_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesswhatsappprofile',
            name='business_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_whatsapp_profile', to='neksio_api.businessprofile'),
        ),
    ]
