# Generated by Django 5.0.9 on 2025-08-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0014_alter_businesswhatsappprofile_business_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswhatsappprofile',
            name='authorize_key',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
