# Generated by Django 5.0.14 on 2025-08-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0015_businesswhatsappprofile_authorize_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswhatsappprofile',
            name='data_collection',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
