# Generated by Django 5.0.14 on 2025-08-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0016_businesswhatsappprofile_data_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswhatsappprofile',
            name='admin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
