# Generated by Django 5.0.14 on 2025-08-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0017_businesswhatsappprofile_admin_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesswhatsappprofile',
            name='whatsapp_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
