# Generated by Django 5.0.14 on 2025-09-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0019_whatsappcontacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
