# Generated by Django 5.0.14 on 2025-10-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0020_parties_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsetting',
            name='closing_balance',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='closing balance'),
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='opening_balance',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='opening balance'),
        ),
    ]
