# Generated by Django 5.0.14 on 2025-10-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0021_accountsetting_closing_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxtypes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxtypes',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
