# Generated by Django 5.0.14 on 2025-10-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0022_alter_taxtypes_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesettings',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
