from django.db import models


class ProductChoices(models.TextChoices):
    SERVICE = "Service", "Service"
    PRODUCT = "Product", "Product"
    GROUP = "Group", "Group"
    RECIPE = "Recipe", "Recipe"
    RAW_MATERIAL = "Raw Material", "Raw Material"


class TransactionChoices(models.TextChoices):
    SALE = "SALE", "SALE"
    SALE_REFUND = "SALE_REFUND", "SALE_REFUND"
    PURCHASE = "PURCHASE", "PURCHASE"
    PURCHASE_REFUND = "PURCHASE_REFUND", "PURCHASE_REFUND"
    JOURNAL_ENTRY = "JOURNAL_ENTRY", "JOURNAL_ENTRY"
    PAYMENT_VOUCHER = "PAYMENT_VOUCHER", "PAYMENT_VOUCHER"
    OPENING_BALANCE = "OPENING_BALANCE", "OPENING_BALANCE"
    RECEIPT_VOUCHER = "RECEIPT_VOUCHER", "RECEIPT_VOUCHER"
    CREDIT_NOTE = "CREDIT_NOTE", "CREDIT_NOTE"
    DEBIT_NOTE = "DEBIT_NOTE", "DEBIT_NOTE"
    REVERSE_PAYMENT_ENTRY = "REVERSE_PAYMENT_VOUCHER", "REVERSE_PAYMENT_VOUCHER"
    REVERSE_RECEIPT_VOUCHER = "REVERSE_RECEIPT_VOUCHER", "REVERSE_RECEIPT_VOUCHER"
    REVERSE_JOURNAL_ENTRY = "REVERSE_JOURNAL_ENTRY", "REVERSE_JOURNAL_ENTRY"


class TransactionStatusChoices(models.TextChoices):
    PENDING = "PENDING", "PENDING"
    PROCESSING = "PROCESSING", "PROCESSING"
    COMPLETED = "COMPLETED", "COMPLETED"
    REJECTED = "REJECTED", "REJECTED"
    CANCELLED = "CANCELLED", "CANCELED"


class TaxInvoiceChoices(models.TextChoices):
    REPORTING_INVOICE = "REPORTING_INVOICE", "REPORTING_INVOICE"
    REPORTING_CREDIT_NOTE = "REPORTING_CREDIT_NOTE", "REPORTING_CREDIT_NOTE"
    REPORTING_DEBIT_NOTE = "REPORTING_DEBIT_NOTE", "REPORTING_DEBIT_NOTE"
    CLEARANCE_INVOICE = "CLEARANCE_INVOICE", "CLEARANCE_INVOICE"
    CLEARANCE_CREDIT_NOTE = "CLEARANCE_CREDIT_NOTE", "CLEARANCE_CREDIT_NOTE"
    CLEARANCE_DEBIT_NOTE = "CLEARANCE_DEBIT_NOTE", "CLEARANCE_DEBIT_NOTE"


class TaxStatusChoices(models.TextChoices):
    CLEARED = "CLEARED", "CLEARED"
    NOT_CLEARED = "NOT_CLEARED", "NOT_CLEARED"
    REPORTED = "REPORTED", "REPORTED"
    NOT_REPORTED = "NOT_REPORTED", "NOT_REPORTED"
