# Generated by Django 5.0.9 on 2025-07-16 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neksio_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication_token', models.TextField(blank=True, max_length=2500)),
                ('seller_name', models.CharField(blank=True, max_length=230)),
                ('tax_no', models.CharField(blank=True, max_length=16)),
                ('common_name', models.CharField(blank=True, max_length=230)),
                ('organisation', models.CharField(blank=True, max_length=230)),
                ('organisation_unit', models.CharField(blank=True, max_length=230)),
                ('serial_number', models.CharField(blank=True, max_length=230)),
                ('title', models.CharField(blank=True, max_length=230)),
                ('registered_address', models.CharField(blank=True, max_length=230)),
                ('business_category', models.CharField(blank=True, max_length=230)),
                ('otp', models.CharField(blank=True, max_length=230)),
                ('enable_zatca', models.BooleanField(blank=True, default=False)),
                ('schemeType', models.CharField(blank=True, choices=[('TIN', 'TIN'), ('GCC', 'GCC'), ('IQA', 'IQA'), ('PAS', 'PAS'), ('CRN', 'CRN'), ('MOM', 'MOM'), ('MLS', 'MLS'), ('700', '700'), ('SAG', 'SAG'), ('OTH', 'OTH')], max_length=50, null=True, verbose_name='Scheme ID')),
                ('schemeNo', models.BigIntegerField(blank=True, null=True, verbose_name='Scheme Number')),
                ('StreetName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Name')),
                ('BuildingNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Building Number')),
                ('PlotIdentification', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plot Identification')),
                ('CitySubdivisionName', models.CharField(blank=True, max_length=255, null=True, verbose_name='City Subdivision Name')),
                ('CityName', models.CharField(blank=True, max_length=255, null=True, verbose_name='City Name')),
                ('PostalZone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal Zone')),
                ('TaxScheme', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Type')),
                ('xml_text', models.TextField(blank=True, null=True, verbose_name='XML Text')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='neksio_api.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(blank=True, max_length=1000)),
                ('public_key', models.TextField(blank=True, max_length=1000)),
                ('csr', models.TextField(blank=True, max_length=2500)),
                ('csid', models.TextField(blank=True, max_length=3500)),
                ('csid_base64', models.TextField(blank=True, max_length=3500)),
                ('secret_csid', models.TextField(blank=True, max_length=2500)),
                ('csid_request', models.TextField(blank=True, max_length=100)),
                ('x509_base64', models.TextField(blank=True, max_length=3500)),
                ('x509_certificate', models.TextField(blank=True, max_length=3500)),
                ('x509_secret', models.TextField(blank=True, max_length=500)),
                ('x509_request', models.TextField(blank=True, max_length=100)),
                ('location', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='production', to='zatca_api.businesslocation')),
            ],
        ),
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(blank=True, max_length=1000)),
                ('public_key', models.TextField(blank=True, max_length=1000)),
                ('csr', models.TextField(blank=True, max_length=2500)),
                ('csid', models.TextField(blank=True, max_length=3500, null=True)),
                ('csid_base64', models.TextField(blank=True, max_length=3500, null=True)),
                ('secret_csid', models.TextField(blank=True, max_length=2500, null=True)),
                ('csid_request', models.TextField(blank=True, max_length=100, null=True)),
                ('x509_base64', models.TextField(blank=True, max_length=3500, null=True)),
                ('x509_certificate', models.TextField(blank=True, max_length=3500, null=True)),
                ('x509_secret', models.TextField(blank=True, max_length=500, null=True)),
                ('x509_request', models.TextField(blank=True, max_length=100, null=True)),
                ('location', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandbox', to='zatca_api.businesslocation')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField(blank=True, max_length=1000)),
                ('public_key', models.TextField(blank=True, max_length=1000)),
                ('csr', models.TextField(blank=True, max_length=2500)),
                ('csid', models.TextField(blank=True, max_length=3500)),
                ('csid_base64', models.TextField(blank=True, max_length=3500)),
                ('secret_csid', models.TextField(blank=True, max_length=2500)),
                ('csid_request', models.TextField(blank=True, max_length=100)),
                ('x509_base64', models.TextField(blank=True, max_length=3500)),
                ('x509_certificate', models.TextField(blank=True, max_length=3500)),
                ('x509_secret', models.TextField(blank=True, max_length=500)),
                ('x509_request', models.TextField(blank=True, max_length=100)),
                ('location', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation', to='zatca_api.businesslocation')),
            ],
        ),
    ]
