# Generated by Django 5.0.9 on 2025-07-16 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZatcaInvoicesProduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoiceNo', models.CharField(max_length=50)),
                ('invoiceType', models.CharField(max_length=50)),
                ('documentType', models.CharField(max_length=50)),
                ('invoiceUuid', models.CharField(max_length=150)),
                ('invoiceHash', models.TextField(blank=True)),
                ('invoiceBase64', models.TextField(blank=True)),
                ('invoiceQrcode', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('warning', 'warning'), ('failed', 'failed')], max_length=50)),
                ('status_code', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True)),
                ('compliance', models.BooleanField(default=False)),
                ('invoiceScope', models.CharField(blank=True, choices=[('sandbox', 'Sandbox'), ('simulation', 'Simulation'), ('production', 'production')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
