# Generated by Django 5.0.9 on 2025-07-16 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('zatca_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zatcainvoicesproduction',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='productionInvoices', to='zatca_api.businesslocation'),
        ),
    ]
