# Generated by Django 5.0.9 on 2025-07-16 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('neksio_api', '0002_initial'),
        ('zatca_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='business_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='neksio_api.businessprofile'),
        ),
        migrations.AddField(
            model_name='users',
            name='default_business_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zatca_api.businesslocation'),
        ),
        migrations.AddField(
            model_name='users',
            name='display_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='neksio_api.mediafiles'),
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='PartiesAccounts',
            fields=[
                ('masteraccounts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.masteraccounts')),
                ('schemeID', models.CharField(blank=True, max_length=5, verbose_name='Scheme ID')),
                ('schemeNo', models.BigIntegerField(blank=True, null=True, verbose_name='Scheme Number')),
                ('streetName', models.CharField(blank=True, max_length=50, verbose_name='Street Name')),
                ('buildingNumber', models.CharField(blank=True, max_length=50, verbose_name='Building Number')),
                ('plotIdentification', models.CharField(blank=True, max_length=50, verbose_name='Plot Identification')),
                ('citySubdivisionName', models.CharField(blank=True, max_length=50, verbose_name='City Subdivision Name')),
                ('cityName', models.CharField(blank=True, max_length=50, verbose_name='City Name')),
                ('postalZone', models.CharField(blank=True, max_length=10, verbose_name='Postal Zone')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='Country')),
                ('companyTaxNo', models.BigIntegerField(blank=True, null=True, verbose_name='Company Tax No')),
                ('taxScheme', models.CharField(blank=True, max_length=5, verbose_name='Tax Scheme')),
                ('registrationName', models.CharField(blank=True, max_length=60, verbose_name='Registration Name')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.masteraccounts',),
        ),
        migrations.AddField(
            model_name='masteraccounts',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_accounts', to='zatca_api.businesslocation'),
        ),
        migrations.AddField(
            model_name='masteraccounts',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.masteraccounts'),
        ),
        migrations.AddField(
            model_name='rolegroup',
            name='default_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zatca_api.businesslocation'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.rolegroup'),
        ),
    ]
