# Generated by Django 5.0.9 on 2025-07-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='collections',
            field=models.TextField(blank=True, null=True),
        ),
    ]
