# Generated by Django 5.0.14 on 2025-07-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningtable',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='table_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
