# Generated by Django 5.0.14 on 2025-07-31 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neksio_api', '0006_rename_financial_account_employees_chart_of_account'),
        ('products', '0002_alter_diningtable_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupItems',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_data', to='neksio_api.businessprofile')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_data', to='products.productitem')),
            ],
            options={
                'verbose_name': 'Group Items',
                'verbose_name_plural': 'Group Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
