# Generated by Django 5.0.14 on 2025-07-31 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_groupitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_items', to='products.productitem'),
        ),
    ]
