# Generated by Django 5.0.14 on 2025-07-31 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_groupitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupitems',
            name='child_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_items', to='products.productitem'),
        ),
        migrations.AlterField(
            model_name='groupitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_item', to='products.productitem'),
        ),
    ]
