# Generated by Django 5.0.14 on 2025-08-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_groupitems_child_item_alter_groupitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningtable',
            name='table_number',
            field=models.CharField(max_length=50),
        ),
    ]
