# Generated by Django 5.0.9 on 2025-09-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_diningtable_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='item_type',
            field=models.CharField(choices=[('raw', 'RAW'), ('menu', 'Menu'), ('sale', 'Sale Item'), ('device', 'Devices'), ('accessory', 'Accessory')], default='sale', max_length=10),
        ),
    ]
